stages:
    - style
    - build

.debian-amd64-common:
    image: registry.videolan.org/vlc-debian-unstable:20250528090433
    stage: build
    tags:
        - docker
        - amd64

style-check:
    extends: .debian-amd64-common
    stage: style
    script:
        - git grep -I -n -P "\t|\r| $" -- . ':(exclude)*/compat/*' ':(exclude)patches/*' && echo "Trailing whitespace" && exit 1
        - git grep -I -l -z "" -- . ':(exclude)*/compat/*' ':(exclude)patches/*' | while IFS= read -r -d '' i; do
              if grep -n "[$'\u061c'$'\u2000'-$'\u200f'$'\u2028'-$'\u202f'$'\u205f'-$'\u206f']" "$i"; then
                  echo "Invisible Unicode characters";
                  exit 1;
              fi;
              if [ -n "$(tail -c 1 "$i")" ]; then
                  echo "No newline at end of $i";
                  exit 1;
              fi;
          done

build-debian:
    extends: .debian-amd64-common
    tags:
        - docker
        - avx2
        - amd64
    script:
        - set -eo pipefail
        - git clone -b research-v12.0.0 --depth 1 --shallow-submodules
              https://gitlab.com/AOMediaCodec/avm.git avm
        - |
          cd avm
          git config user.name "CI Bot"
          git config user.email "ci-bot@example.com"
          git am ../patches/*.patch
        - |
          sed -i 's|#define DEBUG_OBU_HDR 0|#define DEBUG_OBU_HDR 1|' aom/debug.h
          sed -i 's|#define DEBUG_SEQ_HDR 0|#define DEBUG_SEQ_HDR 1|' aom/debug.h
          sed -i 's|#define DEBUG_FRAME_HDR 0|#define DEBUG_FRAME_HDR 1|' aom/debug.h
          sed -i 's|#define DEBUG_BLOCK_INFO 0|#define DEBUG_BLOCK_INFO 1|' aom/debug.h
          git diff
        - |
          mkdir x86-64
          cd x86-64
          cmake .. -DENABLE_TESTS=0 -DCONFIG_AV1_ENCODER=0
          make -j$(nproc) aomdec
          cd ../..
        - |
          sed -i 's|#define DEBUG_OBU_HDR 0|#define DEBUG_OBU_HDR 1|' src/obu.c
          sed -i 's|#define DEBUG_SEQ_HDR 0|#define DEBUG_SEQ_HDR 1|' src/obu.c
          sed -i 's|#define DEBUG_FRAME_HDR 0|#define DEBUG_FRAME_HDR 1|' src/obu.c
          sed -i 's|#define DEBUG_BLOCK_INFO 0|#define DEBUG_BLOCK_INFO 1|' src/debug.h
          git diff
        - meson setup build -Dtrim_dsp=false && ninja -C build
        - meson test -v -C build
        - |
          for sdp in 0 1; do
              file="media/avm-v12.0.0-sdp${sdp}.ivf"
              avm/x86-64/aomdec $file -o /dev/null > avm.sdp${sdp}.log
              build/tools/dav1d -i $file --muxer=null --threads=1 --quiet > dav1d.sdp${sdp}.log
              diff -uw {avm,dav1d}.sdp${sdp}.log
              wc -l avm.sdp${sdp}.log
          done
        - |
          cd avm
          sed -i 's|#define DEBUG_B_PIXELS 0|#define DEBUG_B_PIXELS 1|' aom/debug.h
          git diff
        - cd x86-64 && make -j$(nproc) aomdec && cd ../..
        - |
          sed -i 's|#define DEBUG_B_PIXELS 0|#define DEBUG_B_PIXELS 1|' src/debug.h
          git diff
        - ninja -C build
        - |
          for sdp in 0 1; do
              file="media/avm-v12.0.0-sdp${sdp}.ivf"
              avm/x86-64/aomdec $file -o /dev/null > avm.sdp${sdp}.log
              build/tools/dav1d -i $file --muxer=null --threads=1 --quiet > dav1d.sdp${sdp}.log
              diff -uw {avm,dav1d}.sdp${sdp}.log
              wc -l avm.sdp${sdp}.log
          done
        - |
          cd avm
          sed -i 's|#define DEBUG_B_PIXELS 1|#define DEBUG_B_PIXELS 0|' aom/debug.h
          sed -i 's|cm->current_frame.frame_number == 0|cm->current_frame.frame_number <= 4|' aom/debug.h
          git diff
        - cd x86-64 && make -j$(nproc) aomdec && cd ../..
        - |
          sed -i 's|#define DEBUG_B_PIXELS 1|#define DEBUG_B_PIXELS 0|' src/debug.h
          sed -i 's|f->frame_hdr->frame_offset == 0|f->frame_hdr->frame_offset <= 4|' src/debug.h
          git diff
        - ninja -C build
        - |
          file="media/avm-v12.0.0-bus.64x64.l5.ivf"
          # refmvs is not yet implemented, so discard these parts of the entropy debugging log
          avm/x86-64/aomdec $file -o /dev/null | grep -v ' mv\[' > avm.inter.log
          build/tools/dav1d -i $file --muxer=null --threads=1 --quiet | grep -v ' mv\[' > dav1d.inter.log
          diff -uw {avm,dav1d}.inter.log
          wc -l avm.inter.log
