stages:
    - style
    - build

.debian-amd64-common:
    image: registry.videolan.org/vlc-debian-unstable:20250528090433
    stage: build
    tags:
        - docker
        - amd64

style-check:
    extends: .debian-amd64-common
    stage: style
    script:
        - git grep -I -n -P "\t|\r| $" -- . ':(exclude)*/compat/*' ':(exclude)patches/*' && echo "Trailing whitespace" && exit 1
        - git grep -I -l -z "" -- . ':(exclude)*/compat/*' ':(exclude)patches/*' | while IFS= read -r -d '' i; do
              if grep -n "[$'\u061c'$'\u2000'-$'\u200f'$'\u2028'-$'\u202f'$'\u205f'-$'\u206f']" "$i"; then
                  echo "Invisible Unicode characters";
                  exit 1;
              fi;
              if [ -n "$(tail -c 1 "$i")" ]; then
                  echo "No newline at end of $i";
                  exit 1;
              fi;
          done

build-debian:
    extends: .debian-amd64-common
    tags:
        - docker
        - avx2
        - amd64
    script:
        - set -eo pipefail
        - git clone -b research-v12.0.0 --depth 1 --shallow-submodules
              https://gitlab.com/AOMediaCodec/avm.git avm
        - |
          cd avm
          git config user.name "CI Bot"
          git config user.email "ci-bot@example.com"
          git am ../patches/*.patch
        - |
          sed -i 's|#define DEBUG_OBU_HDR 0|#define DEBUG_OBU_HDR 1|' aom/debug.h
          sed -i 's|#define DEBUG_SEQ_HDR 0|#define DEBUG_SEQ_HDR 1|' aom/debug.h
          sed -i 's|#define DEBUG_FRAME_HDR 0|#define DEBUG_FRAME_HDR 1|' aom/debug.h
          sed -i 's|#define DEBUG_BLOCK_INFO 0|#define DEBUG_BLOCK_INFO 1|' aom/debug.h
          git diff
        - |
          mkdir x86-64
          cd x86-64
          cmake .. -DENABLE_TESTS=0 -DCONFIG_AV1_ENCODER=0
          make -j$(nproc) aomdec
          cd ../..
        - |
          sed -i 's|#define DEBUG_OBU_HDR 0|#define DEBUG_OBU_HDR 1|' src/obu.c
          sed -i 's|#define DEBUG_SEQ_HDR 0|#define DEBUG_SEQ_HDR 1|' src/obu.c
          sed -i 's|#define DEBUG_FRAME_HDR 0|#define DEBUG_FRAME_HDR 1|' src/obu.c
          sed -i 's|#define DEBUG_BLOCK_INFO 0|#define DEBUG_BLOCK_INFO 1|' src/debug.h
          git diff
        - meson setup build -Dtrim_dsp=false && ninja -C build
        - meson test -v -C build
        - |
          for sdp in 0 1; do
              file="media/avm-v12.0.0-sdp${sdp}.ivf"
              avm/x86-64/aomdec $file -o /dev/null > avm.sdp${sdp}.log
              build/tools/dav1d -i $file --muxer=null --threads=1 --quiet > dav1d.sdp${sdp}.log
              diff -uw {avm,dav1d}.sdp${sdp}.log
              wc -l avm.sdp${sdp}.log
          done
        - |
          cd avm
          sed -i 's|#define DEBUG_B_PIXELS 0|#define DEBUG_B_PIXELS 1|' aom/debug.h
          git diff
        - cd x86-64 && make -j$(nproc) aomdec && cd ../..
        - |
          sed -i 's|#define DEBUG_B_PIXELS 0|#define DEBUG_B_PIXELS 1|' src/debug.h
          git diff
        - ninja -C build
        - |
          for sdp in 0 1; do
              file="media/avm-v12.0.0-sdp${sdp}.ivf"
              avm/x86-64/aomdec $file -o /dev/null > avm.sdp${sdp}.log
              build/tools/dav1d -i $file --muxer=null --threads=1 --quiet > dav1d.sdp${sdp}.log
              diff -uw {avm,dav1d}.sdp${sdp}.log
              wc -l avm.sdp${sdp}.log
          done
        - |
          cd avm
          sed -i 's|#define DEBUG_B_PIXELS 1|#define DEBUG_B_PIXELS 0|' aom/debug.h
          sed -i 's|cm->current_frame.frame_number == 0|cm->current_frame.frame_number <= 4|' aom/debug.h
          git diff
        - cd x86-64 && make -j$(nproc) aomdec && cd ../..
        - |
          sed -i 's|#define DEBUG_B_PIXELS 1|#define DEBUG_B_PIXELS 0|' src/debug.h
          sed -i 's|frame_offset == 0|frame_offset <= 4|' src/debug.h
          git diff
        - ninja -C build
        - |
          file="media/avm-v12.0.0-bus.64x64.l5.ivf"
          # refmvs is not yet fully implemented, so discard these parts of the entropy debugging log
          avm/x86-64/aomdec $file -o /dev/null | grep -v ' mv\[' | grep -v 2dmv > avm.inter.log
          build/tools/dav1d -i $file --muxer=null --threads=1 --quiet | grep -v ' mv\[' | grep -v 2dmv > dav1d.inter.log
          diff -uw {avm,dav1d}.inter.log
          wc -l avm.inter.log
        - |
          cd avm
          sed -i 's|#define DEBUG_REFMV 0|#define DEBUG_REFMV 1|' av1/common/mvref_common.c
          git diff
        - cd x86-64 && make -j$(nproc) aomdec && cd ../..
        - |
          sed -i 's|#define DEBUG_REFMV 0|#define DEBUG_REFMV 1|' src/refmvs.c
          git diff
        - ninja -C build
        - |
          file="media/avm-v12.0.0-bus.64x64.l5.opfl0-refinemv0.ivf"
          avm/x86-64/aomdec $file -o /dev/null > avm.inter.log
          build/tools/dav1d -i $file --muxer=null --threads=1 --quiet > dav1d.inter.log
          diff -uw {avm,dav1d}.inter.log
          wc -l avm.inter.log
        - |
          cd avm
          git reset --hard
        - cd x86-64 && make -j$(nproc) aomdec && cd ../..
        - |
          git reset --hard
        - ninja -C build
        - |
          echo "[CI] Running AVM vs DAV2D MD5 regression test"
          files=(
              "./media/avm-v12.0.0-sdp0.ivf"
              "./media/avm-v12.0.0-sdp1.ivf"
              "./media/avm-v12.0.0-bus.64x64.l5.ivf"
              "./media/avm-v12.0.0-bus.64x64.l5.opfl0-refinemv0.ivf"
          )
          for file in "${files[@]}"; do
              base="$(basename "$file")"
              a_file="/tmp/${base}.avm.yuv"
              d_file="/tmp/${base}.dav2d.yuv"
              ./avm/x86-64/aomdec "$file" -o "$a_file" --limit=1 --inloopfilters=deblock+cdef --rawvideo
              ./build/tools/dav1d -i "$file" -o "$d_file" --limit=1 --inloopfilters=deblock+cdef --threads=1 --quiet
              a_md5=$(head -c "$((64 * 64))" "$a_file" | md5sum | cut -d' ' -f1)
              d_md5=$(head -c "$((64 * 64))" "$d_file" | md5sum | cut -d' ' -f1)
              if [[ "$a_md5" == "$d_md5" ]]; then
                  echo $base "[OK] md5:$a_md5"
              else
                  echo $base "[FAILED!]"
                  diff <(echo "$a_md5") <(echo "$d_md5")
              fi
          done
          files=(
              "./media/avm-v12.0.0-bus.64x64.l5.opfl0-refinemv0.ivf"
          )
          for file in "${files[@]}"; do
              base="$(basename "$file")"
              a_file="/tmp/${base}.avm.yuv"
              d_file="/tmp/${base}.dav2d.yuv"
              ./avm/x86-64/aomdec "$file" -o "$a_file" --inloopfilters=deblock --rawvideo
              ./build/tools/dav1d -i "$file" -o "$d_file" --inloopfilters=deblock --filmgrain=0 --threads=1 --quiet
              a_md5=$(for i in `seq 0 4`; do head -c "$((64 * 64 + 64 * 96 * $i))" $a_file | tail -c "$((64 * 64))"; done | md5sum | cut -d' ' -f1)
              d_md5=$(for i in `seq 0 4`; do head -c "$((64 * 64 + 64 * 96 * $i))" $d_file | tail -c "$((64 * 64))"; done | md5sum | cut -d' ' -f1)
              if [[ "$a_md5" == "$d_md5" ]]; then
                  echo $base "[OK] md5:$a_md5"
              else
                  echo $base "[FAILED!]"
                  diff <(echo "$a_md5") <(echo "$d_md5")
              fi
          done
          files=(
              "./media/avm-v12.0.0-sdp0-cctx0.ivf"
          )
          for file in "${files[@]}"; do
              base="$(basename "$file")"
              a_file="/tmp/${base}.avm.yuv"
              d_file="/tmp/${base}.dav2d.yuv"
              a_md5=$(./avm/x86-64/aomdec "$file" -o - --inloopfilters=deblock+cdef --md5 --rawvideo | cut -d' ' -f1)
              d_md5=$(./build/tools/dav1d -i "$file" -o - --inloopfilters=deblock+cdef --threads=1 --quiet --muxer=md5)
              if [[ "$a_md5" == "$d_md5" ]]; then
                  echo $base "[OK] md5:$a_md5"
              else
                  echo $base "[FAILED!]"
                  diff <(echo "$a_md5") <(echo "$d_md5")
              fi
          done

