stages:
    - style
    - build

.debian-amd64-common:
    image: registry.videolan.org/vlc-debian-unstable:20250528090433
    stage: build
    tags:
        - docker
        - amd64

.debian-aarch64-common:
    image: registry.videolan.org/dav1d-debian-bookworm-aarch64:20250215002814
    stage: build
    tags:
        - docker
        - aarch64

.debian-armv7-common:
    image: registry.videolan.org/dav1d-debian-bookworm-armv7:20250215014239
    stage: build
    tags:
        - docker
        - armv7

style-check:
    extends: .debian-amd64-common
    stage: style
    script:
        - git grep -I -n -P "\t|\r| $" -- . ':(exclude)*/compat/*' ':(exclude)patches/*' && echo "Trailing whitespace" && exit 1
        - git grep -I -l -z "" -- . ':(exclude)*/compat/*' ':(exclude)patches/*' | while IFS= read -r -d '' i; do
              if grep -n "[$'\u061c'$'\u2000'-$'\u200f'$'\u2028'-$'\u202f'$'\u205f'-$'\u206f']" "$i"; then
                  echo "Invisible Unicode characters";
                  exit 1;
              fi;
              if [ -n "$(tail -c 1 "$i")" ]; then
                  echo "No newline at end of $i";
                  exit 1;
              fi;
          done

build-debian:
    extends: .debian-amd64-common
    tags:
        - docker
        - avx2
        - amd64
    script:
        - set -eo pipefail
        - git clone -b research-v14.1.0 --depth 1 --shallow-submodules
              https://gitlab.com/AOMediaCodec/avm.git avm
        - |
          cd avm
          git config user.name "CI Bot"
          git config user.email "ci-bot@example.com"
          git am ../patches/*.patch
        - |
          sed -i 's|#define DEBUG_OBU_HDR 0|#define DEBUG_OBU_HDR 1|' avm/debug.h
          sed -i 's|#define DEBUG_SEQ_HDR 0|#define DEBUG_SEQ_HDR 1|' avm/debug.h
          sed -i 's|#define DEBUG_FRAME_HDR 0|#define DEBUG_FRAME_HDR 1|' avm/debug.h
          sed -i 's|#define DEBUG_BLOCK_INFO 0|#define DEBUG_BLOCK_INFO 1|' avm/debug.h
          sed -i 's|#define DEBUG_B_PIXELS 0|#define DEBUG_B_PIXELS 1|' avm/debug.h
          sed -i 's|#define DEBUG_REFMV 0|#define DEBUG_REFMV 1|' av2/common/mvref_common.c
          sed -i 's|#define DEBUG_CI_HDR 0|#define DEBUG_CI_HDR 1|' av2/decoder/obu_ci.c
          sed -i 's|#define DEBUG_FGM_HDR 0|#define DEBUG_FGM_HDR 1|' av2/decoder/obu_fgm.c
          sed -i 's|cm->current_frame.frame_number == 0|cm->current_frame.frame_number <= 4|' avm/debug.h
          git diff
        - |
          mkdir x86-64
          cd x86-64
          cmake .. -DENABLE_TESTS=0 -DCONFIG_AV2_ENCODER=0
          make -j$(nproc) avmdec
          cd ../..
        - |
          sed -i 's|#define DEBUG_OBU_HDR 0|#define DEBUG_OBU_HDR 1|' src/obu.c
          sed -i 's|#define DEBUG_SEQ_HDR 0|#define DEBUG_SEQ_HDR 1|' src/obu.c
          sed -i 's|#define DEBUG_FRAME_HDR 0|#define DEBUG_FRAME_HDR 1|' src/obu.c
          sed -i 's|#define DEBUG_BLOCK_INFO 0|#define DEBUG_BLOCK_INFO 1|' src/debug.h
          sed -i 's|#define DEBUG_B_PIXELS 0|#define DEBUG_B_PIXELS 1|' src/debug.h
          sed -i 's|#define DEBUG_REFMV 0|#define DEBUG_REFMV 1|' src/refmvs.c
          sed -i 's|#define DEBUG_CI_HDR 0|#define DEBUG_CI_HDR 1|' src/obu.c
          sed -i 's|#define DEBUG_FGM_HDR 0|#define DEBUG_FGM_HDR 1|' src/obu.c
          sed -i 's|frame_offset == 0|frame_offset <= 4|' src/debug.h
          git diff
        - meson setup build --buildtype debugoptimized -Dtrim_dsp=false && ninja -C build
        - meson test -v -C build
        - ninja -C build
        - |
          files=(
              "./media/avm-v14.1.0-bus.64x64.l1.sdp0.obu"
              "./media/avm-v14.1.0-bus.64x64.l1.sdp1.obu"
              "./media/avm-v14.1.0-bus.64x64.l5.obu"
              "./media/avm-v14.1.0-bus.64x64.l5.opfl0-refinemv0.obu"
              "./media/avm-v14.1.0-bus.64x64.l5.lossless.obu"
              "./media/avm-v14.1.0-hm.64x64.l5.filmgrain.obu"
          )
          for file in "${files[@]}"; do
              avm/x86-64/avmdec $file -o /dev/null > avm.log
              build/tools/dav2d -i $file --muxer=null --threads=1 --quiet > dav2d.log
              diff -uw {avm,dav2d}.log
              wc -l avm.log
          done
        - |
          git reset --hard
        - ninja -C build
        - |
          echo "[CI] Running AVM vs DAV2D MD5 regression test"
          time tests/check-md5.sh build/tools/dav2d

build-debian-avx512:
    extends: .debian-amd64-common
    tags:
        - docker
        - amd64-avx512
    variables:
        CFLAGS: '-mavx'
    script:
        - meson setup build --buildtype debugoptimized
        - ninja -C build
        - cd build
        - time meson test -v --suite checkasm

test-win64:
    extends: .debian-amd64-common
    image: registry.videolan.org/dav1d-debian-unstable:20260103195850
    script:
        - wineserver -p && wine wineboot
        - meson setup build --buildtype release
                            -Dlogging=false
                            -Dtrim_dsp=false
                            --cross-file package/crossfiles/x86_64-w64-mingw32.meson
        - ninja -C build
        - cd build && time meson test -v

build-debian-aarch64:
    extends: .debian-aarch64-common
    script:
        - meson setup build --buildtype debugoptimized
                            -Dtrim_dsp=false
        - ninja -C build
        - meson test -v -C build
        - time tests/check-md5.sh build/tools/dav2d

build-debian-armv7:
    extends: .debian-armv7-common
    script:
        - linux32 meson setup build --buildtype debugoptimized
                            -Dtrim_dsp=false
        - ninja -C build
        - meson test -v -C build
        - time tests/check-md5.sh build/tools/dav2d
