name: dav2d
base: core18
version: git
version-script: git describe HEAD --always
summary: AV2 decoder from VideoLAN
description: |
  A small and fast AV2 decoder from the people who brought you VLC.

grade: stable
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  dav2d:
    command: usr/bin/dav2d
    plugs: [ 'home' ]

parts:
  dav2d:
    plugin: meson
    source: ../../
    build-packages: [ 'nasm' ]
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
