name: Builds
on:
  push:

jobs:
  test-toolchain:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - i686
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            unzip
            git
            make
      - name: Unpack toolchain
        run: |
          curl -LO https://github.com/mstorsjo/llvm-mingw/releases/download/20230130/llvm-mingw-20230130-ucrt-${{matrix.arch}}.zip
          unzip -q llvm-mingw-*.zip
          rm llvm-mingw-*.zip
          mv llvm-mingw-* /llvm-mingw
          echo /llvm-mingw/bin >> $GITHUB_PATH
      - uses: actions/checkout@v3
      - name: Build patched mingw-w64
        run: |
          git config --global user.name "LLVM MinGW"
          git config --global user.email root@localhost
          ./build-mingw-w64.sh --skip-include-triplet-prefix /llvm-mingw
