name: Builds
on:
  push:
    branches:
      - '**'

jobs:
  inspect:
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-22.04-arm
          - ubuntu-24.04-arm
    runs-on: ${{matrix.image}}
    steps:
      - name: Inspect
        run: |
            set -x
            uname -m
            nproc
            cat /proc/cpuinfo
            df -h
            ls /etc/apt/apt.conf.d/
            cat /etc/apt/apt.conf.d/90assumeyes
