name: Builds
on:
  push:
  pull_request:

jobs:
  test-msvc-wine-macos:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - macos-12
          - macos-13
          - macos-14
    runs-on: ${{matrix.runner}}
    steps:
      - name: Install prerequisites
        run: |
          set -x
          ls -l /usr/local/bin/2to3*
          time brew list --versions
          time brew install msitools cmake ninja meson
          time brew update --auto-update
          time brew install wine-stable
