name: Builds
on:
  push:

jobs:
  test-toolchain:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - i686
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            unzip
            make
      - name: Unpack toolchain
        run: |
          curl -LO https://github.com/mstorsjo/llvm-mingw/releases/download/20230320/llvm-mingw-20230320-ucrt-${{matrix.arch}}.zip
          unzip -q llvm-mingw-*.zip
          rm llvm-mingw-*.zip
          mv llvm-mingw-* /llvm-mingw
          echo /llvm-mingw/bin >> $GITHUB_PATH
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          ./run-tests.sh /llvm-mingw
          ./run-lldb-tests.sh /llvm-mingw

  # Run llvm-mingw's tests on x86_64 with wine, on Linux.
  test-toolchain-wine:
    runs-on: ubuntu-latest
    steps:
      - name: Install wine
        run: |
          # dpkg --add-architecture i386 to install 32 bit wine fails currently
          sudo apt-get update && sudo apt-get install wine64-development
          wine64 wineboot
      - name: Set up wine-arm64
        run: |
          docker pull linaro/wine-arm64
          echo "#!/bin/sh" > wine-arm64
          echo "EXE=\"\$1\"" >> wine-arm64
          echo "shift" >> wine-arm64
          echo "case \"\$EXE\" in" >> wine-arm64
          echo "/*) BASE=\"\$(dirname \"\$EXE\")\" ;;" >> wine-arm64
          echo "*) BASE=\"\$(pwd)\"; EXE=\"\$BASE/\$EXE\" ;;" >> wine-arm64
          echo "esac" >> wine-arm64
          echo "docker run --rm -v \"\$BASE:\$BASE\" linaro/wine-arm64 wine-arm64 \"\$EXE\" \"\$@\"" >> wine-arm64
          chmod a+x wine-arm64
          sudo mkdir -p /opt/wine-arm64/bin
          sudo mv wine-arm64 /opt/wine-arm64/bin
          echo /opt/wine-arm64/bin >> $GITHUB_PATH
      - name: Unpack cross toolchain
        run: |
          curl -LO https://github.com/mstorsjo/llvm-mingw/releases/download/20230320/llvm-mingw-20230320-ucrt-ubuntu-18.04-x86_64.tar.xz
          tar -Jxf llvm-mingw-*.tar.xz
          rm llvm-mingw-*.tar.xz
          sudo mv llvm-mingw* /opt/llvm-mingw
          echo /opt/llvm-mingw/bin >> $GITHUB_PATH
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          RUN_I686=false RUN_X86_64=wine64 RUN_AARCH64=wine-arm64 ./run-tests.sh /opt/llvm-mingw
