name: Builds
on:
  push:
    branches:
      - '**'

jobs:
  inspect:
    runs-on: ubuntu-latest
    container: ghcr.io/btbn/ffmpeg-builds/win64-gpl:latest
    steps:
      - name: Inspect
        env:
          WINEPREFIX: /root/.wineprefix
        run: |
          whoami
          env
          wine wineboot
