name: Builds
on:
  push:
    branches:
      - '**'

jobs:
  inspect:
    runs-on: ubuntu-22.04-arm
    container: linaro/wine-arm64
    steps:
      - name: Run an executable
        run: |
          curl -LO https://martin.st/temp/hello-aarch64.exe
          wine-arm64 hello-aarch64.exe
