name: Builds
on:
  push:
  pull_request:

jobs:
  wine-arm64:
    runs-on: ubuntu-latest
    container: linaro/wine-arm64
    steps:
      - name: Install prerequisites
        env:
          WINEPREFIX: /tmp/wine-x64-prefix
        run: |
          apt-get update && apt-get install -y --no-install-recommends wine python3 msitools python3-simplejson python3-six ca-certificates cmake ninja-build winbind meson
          wine wineboot
      - uses: actions/checkout@v3
      - name: Download MSVC
        env:
          WINEPREFIX: /tmp/wine-x64-prefix
        run: |
          ./vsdownload.py --accept-license --dest $(pwd)/msvc
          ./install.sh $(pwd)/msvc
      - name: Test using the installed tools
        env:
          WINEPREFIX: /tmp/wine-x64-prefix
        run: |
          test/test.sh $(pwd)/msvc
