name: Builds
on:
  push:
    branches:
      - '**'

jobs:
  test-cache:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - windows-latest
          - windows-11-arm
        variant:
          - ccache
          - sccache
    runs-on: ${{matrix.runner}}
    steps:
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 50M
          key: test-cache-${{matrix.runner}}-${{matrix.variant}}
          variant: ${{matrix.variant}}
