name: Builds
on:
  push:
    branches:
      - '**'

jobs:
  inspect:
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu-22.04-arm
          - ubuntu-24.04-arm
    runs-on: ${{matrix.image}}
    steps:
      - name: Inspect
        run: |
          uname -a
