name: Builds
on:
  push:
    branches:
      - '**'

jobs:
  inspect:
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: ${{matrix.image}}
    steps:
      - name: Inspect available packages
        run: |
          dpkg -l
