name: Builds
on:
  push:

jobs:
  test-llvm:
    strategy:
      fail-fast: false
      matrix:
        image:
          - windows-latest
          - windows-2019
          - windows-2022
    runs-on: ${{matrix.image}}
    steps:
      - name: Build and run tests
        shell: cmd
        run: |
          where cmake
          where ninja
