name: Builds
on:
  push:
  pull_request:

jobs:
  test-msvc-wine-macos:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - macos-13
          - macos-14
          - macos-15
          - macos-latest
    runs-on: ${{matrix.runner}}
    steps:
      - name: Inspect the SDK
        run: |
          uname -a
          echo MAC_OS_X_VERSION_MAX_ALLOWED | clang -E -P -include AvailabilityMacros.h -
