name: Builds
on:
  push:
    branches:
      - '**'

jobs:
  inspect:
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu-22.04-arm
          - ubuntu-24.04-arm
    runs-on: ${{matrix.image}}
    steps:
      - name: Install wine
        run: |
          sudo apt-get update && sudo apt-get install wine64
      - name: Initialize wine
        run: |
          wine wineboot
      - name: Run an executable
        run: |
          curl -LO https://martin.st/temp/hello-aarch64.exe
          wine hello-aarch64.exe
