name: Builds
on:
  push:
    branches:
      - '**'

jobs:
  inspect:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - windows-latest
          - windows-11-arm
    runs-on: ${{matrix.runner}}
    steps:
      - name: Inspect Python
        shell: cmd
        run: |
          where python313.dll
