name: Builds
on:
  push:
  pull_request:

env:
  # From https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#download-icon-step-3-install-wdk
  WDK_INSTALLER_URL: "https://go.microsoft.com/fwlink/?linkid=2249371"

jobs:
  test-msvc-wine-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: |
          sudo dpkg --add-architecture i386 && sudo apt-get update
          sudo apt-get install wine64 wine32 python3 msitools ca-certificates cmake ninja-build winbind meson
          wine64 wineboot
          curl -s -L -O https://github.com/madewokherd/wine-mono/releases/download/wine-mono-5.1.1/wine-mono-5.1.1-x86.msi
          wine64 msiexec /i wine-mono-5.1.1-x86.msi
      - uses: actions/checkout@v4
      - name: Download WDK
        run: |
          WDK_INSTALLERS=$(./wdk-download.sh --cache /var/tmp/msvc-wine "$WDK_INSTALLER_URL")
          echo Downloaded WDK installers to $WDK_INSTALLERS
          mkdir wdk
          mv /var/tmp/msvc-wine/* wdk
      - uses: actions/upload-artifact@v4
        with:
          name: wdk
          path: |
            wdk
          retention-days: 1
