name: Test building ffmpeg

on:
  push:

jobs:
  llvm-mingw-arm:
    runs-on: ubuntu-latest
    container: linaro/wine-arm64
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          set -x
          wine-arm64 wineboot
          wine-arm64 cpu.exe
          wine-arm64 checkasm1.exe
          wine-arm64 checkasm2.exe
          wine-arm64 checkasm3.exe
