name: Builds
on:
  push:

jobs:
  # Run llvm-mingw's tests on x86_64 and i686 with the cross-built corresponding
  # toolchains from above.
  test-toolchain:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            unzip
            make
      - name: Unpack toolchain
        run: |
          curl -LO https://martin.st/temp/nightly-good.zip
          unzip -q *.zip
          rm *.zip
          mv llvm-mingw-* /llvm-mingw
          echo /llvm-mingw/bin >> $GITHUB_PATH
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          NATIVE=1 ./test-libcxx-module.sh /llvm-mingw
          ./run-tests.sh /llvm-mingw
          ./run-lldb-tests.sh /llvm-mingw
