name: Builds
on:
  push:
  pull_request:

jobs:
  test-msvc-wine-macos:
    runs-on: macos-latest
    steps:
      - name: Install prerequisites
        run: |
          set -x
          time brew update
          time brew install ninja
          time brew install cmake
          time brew install wine-stable
          time brew install msitools
          time brew install meson
