name: dav2d CI

on:
  push:
    branches: [dav2d]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ dav2d ]

jobs:
  build-mac:
    if: github.event.pull_request.draft == false
    name: Build and test
    runs-on: ubuntu-24.04

    steps:
    - name: checkout dav2d
      uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install nasm cmake meson ninja-build
    - name: checkout AVM v11.0.0
      run: |
        git clone -b research-v11.0.0 --depth 1 --shallow-submodules https://gitlab.com/AOMediaCodec/avm.git avm
    - name: build AVM v11.0.0
      run: |
        cd avm
        git config user.email "a@b.c"
        git config user.name "test"
        git am ../patches/*.patch
        sed -i 's|#define DEBUG_OBU_HDR 0|#define DEBUG_OBU_HDR 1|' aom/debug.h
        sed -i 's|#define DEBUG_SEQ_HDR 0|#define DEBUG_SEQ_HDR 1|' aom/debug.h
        sed -i 's|#define DEBUG_FRAME_HDR 0|#define DEBUG_FRAME_HDR 1|' aom/debug.h
        sed -i 's|#define DEBUG_BLOCK_INFO 0|#define DEBUG_BLOCK_INFO 1|' aom/debug.h
        git diff
        mkdir x86-64
        cd x86-64
        cmake .. -DENABLE_TESTS=0 -DCONFIG_AV1_ENCODER=0
        make -j$(nproc) aomdec
        cd ../..
    - name: build dav2d
      run: |
        sed -i 's|#define DEBUG_OBU_HDR 0|#define DEBUG_OBU_HDR 1|' src/obu.c
        sed -i 's|#define DEBUG_SEQ_HDR 0|#define DEBUG_SEQ_HDR 1|' src/obu.c
        sed -i 's|#define DEBUG_FRAME_HDR 0|#define DEBUG_FRAME_HDR 1|' src/obu.c
        sed -i 's|#define DEBUG_BLOCK_INFO 0|#define DEBUG_BLOCK_INFO 1|' src/debug.h
        git diff
        meson build -Denable_tests=false
        cd build
        ninja
        cd ..
    - name: run tests
      run: |
        for sdp in 0 1; do
            file="media/avm-v11.0.0-sdp${sdp}.ivf"
            avm/x86-64/aomdec $file -o /dev/null > avm.sdp${sdp}.log
            build/tools/dav1d -i $file --muxer=null --threads=1 --quiet > dav1d.sdp${sdp}.log
            diff -uw {avm,dav1d}.sdp${sdp}.log
            wc -l avm.sdp${sdp}.log
        done
    - name: build AVM v11.0.0 (with reconstruction validation)
      run: |
        cd avm
        sed -i 's|#define DEBUG_B_PIXELS 0|#define DEBUG_B_PIXELS 1|' aom/debug.h
        sed -i 's|mi_row < 16|mi_row < 1|' aom/debug.h
        sed -i 's|mi_col < 16|mi_col < 13|' aom/debug.h
        git diff
        cd x86-64
        make -j$(nproc) aomdec
        cd ../..
    - name: build dav2d (with reconstruction validation)
      run: |
        sed -i 's|#define DEBUG_B_PIXELS 0|#define DEBUG_B_PIXELS 1|' src/debug.h
        sed -i 's|t->by < 16|t->by < 1|' src/debug.h
        sed -i 's|t->bx < 16|t->bx < 13|' src/debug.h
        git diff
        cd build
        ninja
        cd ..
    - name: run tests (with reconstruction validation)
      run: |
        for sdp in 0; do
            file="media/avm-v11.0.0-sdp${sdp}.ivf"
            avm/x86-64/aomdec $file -o /dev/null > avm.sdp${sdp}.log
            build/tools/dav1d -i $file --muxer=null --threads=1 --quiet > dav1d.sdp${sdp}.log
            diff -uw {avm,dav1d}.sdp${sdp}.log
            wc -l avm.sdp${sdp}.log
        done
    - name: build AVM v11.0.0 (with inter entropy)
      run: |
        cd avm
        sed -i 's|#define DEBUG_B_PIXELS 1|#define DEBUG_B_PIXELS 0|' aom/debug.h
        sed -i 's|mi_row < [0-9]\+|mi_row < 16|' aom/debug.h
        sed -i 's|mi_col < [0-9]\+|mi_col < 16|' aom/debug.h
        sed -i 's|cm->current_frame.frame_number == 0|cm->current_frame.frame_number == 4|' aom/debug.h
        git diff
        cd x86-64
        make -j$(nproc) aomdec
        cd ../..
    - name: build dav2d (with inter entropy)
      run: |
        sed -i 's|#define DEBUG_B_PIXELS 1|#define DEBUG_B_PIXELS 0|' src/debug.h
        sed -i 's|t->by < [0-9]\+|t->by < 16|' src/debug.h
        sed -i 's|t->bx < [0-9]\+|t->bx < 16|' src/debug.h
        sed -i 's|f->frame_hdr->frame_offset == 0|f->frame_hdr->frame_offset == 4|' src/debug.h
        git diff
        cd build
        ninja
        cd ..
    - name: run tests (with inter entropy)
      run: |
        file="media/avm-v11.0.0-bus.64x64.l5.ivf"
        avm/x86-64/aomdec $file -o /dev/null > avm.inter.log
        # Only part of the frame will currently parse correctly, so we "catch" the error with "|| true"
        ( build/tools/dav1d -i $file --muxer=null --threads=1 --quiet || true ) > dav1d.inter.log
        for n in avm dav1d; do
            # refmvs is not yet implemented, so discard these parts of the entropy debugging log
            grep -v ' mv\[' ${n}.inter.log | head -n2678 > ${n}.inter.part.log
        done
        diff -uw {avm,dav1d}.inter.part.log
        wc -l avm.inter.part.log
