name: Build docker images
on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to extract from'
        type: string
      branch:
        description: 'Branch to extract from'
        type: string
        default: 'master'
      login:
        description: 'Log in to Docker Hub'
        type: boolean
        default: true
      push:
        description: 'Push the built images'
        type: boolean
        default: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Get build parameters
        run: |
          echo commit "${{inputs.commit}}" branch "${{inputs.branch}}"
