name: Build docker images
on:
  push:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to extract from'
        type: string
      branch:
        description: 'Branch to extract from'
        type: string
        default: 'master'
      login:
        description: 'Log in to Docker Hub'
        type: boolean
        default: true
      push:
        description: 'Push the built images'
        type: boolean
        default: false

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { file: Dockerfile.toolchain, platforms: linux/arm64, key: arm64 }
    steps:
      - uses: actions/checkout@v4
      - name: Download toolchain
        uses: dawidd6/action-download-artifact@v6
        with:
          repo: mstorsjo/llvm-mingw
          workflow: build.yml
          workflow_conclusion: success
          branch: master
          event: push
          name: linux-ucrt-.*
          name_is_regexp: true
          path: toolchain
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker images
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          platforms: ${{matrix.platforms}}
          push: false
          file: ./${{matrix.file}}
