name: Build docker images
on:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: false
          file: ./Dockerfile.toolchain
