name: Build docker images
on:
  push:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to extract from'
        type: string
      branch:
        description: 'Branch to extract from'
        type: string
        default: 'master'
      login:
        description: 'Log in to Docker Hub'
        type: boolean
        default: true
      push:
        description: 'Push the built images'
        type: boolean
        default: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{steps.get-parameters.outputs.TAG}}
    steps:
      - name: Download build parameters
        uses: dawidd6/action-download-artifact@v6
        with:
          repo: mstorsjo/llvm-mingw
          workflow: build.yml
          workflow_conclusion: success
          commit:
          branch: master
          event: push
          name: parameters
      - name: Get build parameters
        id: get-parameters
        run: |
          cat parameters.txt >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  docker-build-dev:
    needs: [prepare]
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        if: false
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          file: ./Dockerfile.dev
          tags: |
            mstorsjo/llvm-mingw:dev
            mstorsjo/llvm-mingw:dev-${{needs.prepare.outputs.TAG}}
      - name: Inspect Docker images
        run: |
          docker images

  docker-build:
    needs: [prepare]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { file: Dockerfile.toolchain, platforms: linux/arm64, key: arm64 }
    steps:
      - name: Download toolchain
        uses: dawidd6/action-download-artifact@v6
        with:
          repo: mstorsjo/llvm-mingw
          workflow: build.yml
          workflow_conclusion: success
          commit:
          branch: master
          event: push
          name: linux-ucrt-.*
          name_is_regexp: true
          path: toolchain
      - name: Inspect Docker images
        run: |
          set -x
          ls -lh
          ls -lh toolchain

  docker-create:
    needs: [docker-build, prepare]
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@main
        id: read
        with:
          matrix-step-name: docker-build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Create final image
        run: |
          set -x
          for tag in latest ${{needs.prepare.outputs.TAG}}; do
              docker buildx imagetools create -t mstorsjo/llvm-mingw:$tag mstorsjo/llvm-mingw@${{fromJson(steps.read.outputs.result).digest.amd64}} mstorsjo/llvm-mingw@${{fromJson(steps.read.outputs.result).digest.arm64}}
          done
