name: Make a release, upload artifacts
on:
  push:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to extract from'
        type: string
      branch:
        description: 'Branch to extract from'
        type: string
        default: 'master'
      tag:
        description: 'Tag to create/upload to'
        required: true
        type: string
      title:
        description: 'Release title'
        type: string
      make_tag:
        description: 'Make a tag'
        type: boolean
        default: true
      create_release:
        description: 'Create release'
        type: boolean
        default: true
      prerelease:
        description: 'Set as pre-release'
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  upload-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          repo: mstorsjo/llvm-mingw
          workflow: build.yml
          workflow_conclusion: success
          commit:
          branch: master
          event: push
      - name: Rearrange files
        run: |
          rm -rf linux-asserts*
          rm -rf msys2*
          mv *-toolchain/*.zip *-toolchain/*.tar.xz .
      - name: Set environment
        run: |
          cat parameters/parameters.txt >> $GITHUB_ENV
      - name: Inspect
        run: |
          ls -lh
