name: Test

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:

jobs:
  main:
    name: main
    runs-on: windows-11-arm

    env:
      CFLAGS: -fuse-ld=lld -fms-runtime-lib=dll -Wall -Wextra

    defaults:
      run: { shell: pwsh }

    steps:
      - uses: actions/checkout@v4

      - name: Download LLVM
        run: |
             curl.exe -LO "https://github.com/llvm/llvm-project/releases/download/llvmorg-20.1.8/clang+llvm-20.1.8-aarch64-pc-windows-msvc.tar.xz"
             tar -xaf clang+llvm-20.1.8-aarch64-pc-windows-msvc.tar.xz
             cvpa clang+llvm-20.1.8-aarch64-pc-windows-msvc/bin | tee -a "${env:GITHUB_PATH}"

      - uses: ilammy/msvc-dev-cmd@v1
        with: { arch: arm64 }

      - name: Build ARM64EC EXE, linking against ARM64EC DLL
        run: |
             cl -arm64EC -MD -c test_dll.c -Fotest_dll.obj
             link -machine:arm64ec -dll test_dll.obj -out:test.dll -implib:test.lib
             cl -arm64EC -MD -c test_exe.c -Fotest_exe.obj
             link -machine:arm64ec test_exe.obj test.lib -out:test.exe
             ./test.exe

      - uses: ilammy/msvc-dev-cmd@v1
        with: { arch: arm64_x64 }

      - name: Rerun ARM64EC EXE, linking against x64 DLL
        run: |
             cl -MD -c test_dll.c -Fotest_dll.obj
             link -dll test_dll.obj -out:test.dll -implib:test.lib
             ./test.exe
