name: Test installing with a system clang
on:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          file: ./Dockerfile.system-clang
